version: '3'

services:
 django:
    build: ./django-app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django-app:/app
    ports:
      - "8000:8000"
    depends_on:
      - ollama
    networks:
      - ollama_network

 ollama:
    image: ollama/ollama
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"
    networks:
      - ollama_network

networks:
 ollama_network:
    driver: bridge

volumes:
 ollama:
