# Generated by Django 4.2.5 on 2023-09-11 20:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Server_Side", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
