# Generated by Django 4.2.5 on 2023-09-20 19:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("Server_Side", "0002_delete_customuser"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField()),
                ("submitted_on", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
