# Generated by Django 4.2.5 on 2023-09-20 19:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Server_Side", "0003_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserQuestion",
        ),
    ]
