# Generated by Django 4.2.5 on 2023-09-28 01:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Server_Side", "0005_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="current_plan",
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AlterField(
            model_name="client",
            name="id_pay",
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="method_pay",
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="subscription_status",
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
