# Generated by Django 4.2.5 on 2023-09-28 01:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Server_Side", "0006_alter_client_current_plan_alter_client_id_pay_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="id_pay",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
