# Generated by Django 4.2.5 on 2023-09-28 01:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Server_Side", "0007_alter_client_id_pay"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="method_pay",
            field=models.PositiveIntegerField(blank=True, default=3),
        ),
    ]
