# Generated by Django 4.2.5 on 2023-09-28 01:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Server_Side", "0008_alter_client_method_pay"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="subscription_status",
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
    ]
