# Generated by Django 4.2.5 on 2023-09-28 02:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Server_Side", "0009_alter_client_subscription_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="CurrentPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_plan", models.CharField(max_length=50)),
            ],
        ),
    ]
