# Generated by Django 4.2.5 on 2023-09-28 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Server_Side", "0010_currentplan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="current_plan",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="Server_Side.currentplan",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="method_pay",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="Server_Side.paymentmethod",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="subscription_status",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="Server_Side.subscriptionstatus",
            ),
        ),
    ]
