# Generated by Django 4.2.5 on 2023-10-05 23:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Server_Side", "0012_client_last_transaction_status_client_order_id"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CurrentPlan",
            new_name="Current_Plan",
        ),
    ]
