# Generated by Django 4.2.5 on 2023-10-14 02:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Server_Side", "0014_usercontext"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserContext",
            new_name="ClienContext",
        ),
    ]
