# Generated by Django 4.2.5 on 2023-10-24 14:31

import Server_Config.Server_Side.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Server_Side", "0015_rename_usercontext_cliencontext"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="current_plan",
            field=models.ForeignKey(
                default=Server_Config.Server_Side.models.Client.get_default_current_plan,
                on_delete=django.db.models.deletion.CASCADE,
                to="Server_Side.current_plan",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="method_pay",
            field=models.ForeignKey(
                default=Server_Config.Server_Side.models.Client.get_default_payment_method,
                on_delete=django.db.models.deletion.CASCADE,
                to="Server_Side.paymentmethod",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="subscription_status",
            field=models.ForeignKey(
                default=Server_Config.Server_Side.models.Client.get_default_subscription_status,
                on_delete=django.db.models.deletion.CASCADE,
                to="Server_Side.subscriptionstatus",
            ),
        ),
    ]
