# Generated by Django 4.2.5 on 2023-11-15 00:44

import Server_Config.Server_Side.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Server_Side", "0015_rename_usercontext_cliencontext"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=200)),
                ("product_id", models.CharField(max_length=200)),
                ("plan_name", models.CharField(max_length=200)),
                ("plan_id", models.CharField(max_length=200)),
                ("name", models.CharField(max_length=200)),
                (
                    "code",
                    models.CharField(
                        default=Server_Config.Server_Side.models.generate_random_code,
                        max_length=5,
                    ),
                ),
                ("price", models.FloatField()),
                ("subscription_date", models.DateField()),
                ("features_list", models.TextField(default="[]")),
                ("market_place", models.TextField(default="[]")),
            ],
        ),
        migrations.RemoveField(
            model_name="client",
            name="current_plan",
        ),
        migrations.RemoveField(
            model_name="client",
            name="id_pay",
        ),
        migrations.RemoveField(
            model_name="client",
            name="method_pay",
        ),
        migrations.RemoveField(
            model_name="client",
            name="subscription_status",
        ),
        migrations.AddField(
            model_name="client",
            name="status_subscription",
            field=models.CharField(default="Inactive", max_length=50),
        ),
        migrations.AddField(
            model_name="client",
            name="total_tokens",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="order_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name="Current_Plan",
        ),
        migrations.DeleteModel(
            name="PaymentMethod",
        ),
        migrations.DeleteModel(
            name="SubscriptionStatus",
        ),
        migrations.AddField(
            model_name="client",
            name="subscription_detail",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Server_Side.subscriptiondetail",
            ),
        ),
    ]
