# Generated by Django 4.2.5 on 2023-10-25 03:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "Server_Side",
            "0016_alter_client_current_plan_alter_client_method_pay_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="total_tokens",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
