# Generated by Django 4.2.5 on 2023-11-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Server_Side", "0016_subscriptiondetail_remove_client_current_plan_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="client",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="client",
            name="date_joined",
        ),
        migrations.RemoveField(
            model_name="client",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="client",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="client",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="client",
            name="is_staff",
        ),
        migrations.RemoveField(
            model_name="client",
            name="is_superuser",
        ),
        migrations.RemoveField(
            model_name="client",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="client",
            name="user_permissions",
        ),
        migrations.RemoveField(
            model_name="client",
            name="username",
        ),
        migrations.AlterField(
            model_name="client",
            name="email",
            field=models.EmailField(
                max_length=255, unique=True, verbose_name="email address"
            ),
        ),
    ]
