# Generated by Django 4.2.5 on 2023-11-24 18:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "Server_Side",
            "0017_alter_client_managers_remove_client_date_joined_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="client",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
    ]
