# Generated by Django 4.2.5 on 2024-05-17 16:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Server_Side", "0019_vectorstore"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vectorstore",
            name="embeddings",
        ),
    ]
