# Generated by Django 4.2.5 on 2024-05-17 17:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Server_Side", "0020_remove_vectorstore_embeddings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vectorstore",
            name="uuid",
            field=models.UUIDField(
                blank=True, default=None, editable=False, null=True, unique=True
            ),
        ),
    ]
