# Generated by Django 4.2.5 on 2024-05-17 17:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Server_Side", "0021_alter_vectorstore_uuid"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="VectorStore",
            new_name="UserRagData",
        ),
    ]
