# Generated by Django 4.2.5 on 2024-05-17 20:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Server_Side", "0022_rename_vectorstore_userragdata"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userragdata",
            name="documents",
        ),
    ]
