# Generated by Django 4.2.5 on 2024-05-17 23:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Server_Side", "0025_userragdata_embedding"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userragdata",
            name="collection_name",
        ),
        migrations.AddField(
            model_name="userragdata",
            name="document_content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
