# Generated by Django 4.2.5 on 2024-05-20 11:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Server_Side", "0026_remove_userragdata_collection_name_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserRagData",
        ),
    ]
